apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-springboot
  title: Spring Boot Microservice
  description: Create a new Spring Boot microservice with Hexagonal Architecture
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - spring-boot
    - java
    - hexagonal
    - microservice
    - jpa
    - mvc
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Información del Componente
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Nombre del Componente
          type: string
          description: Identificador único del componente (ej. user-service)
          default: user-service
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Usar kebab-case: minúsculas y guiones'
        description:
          title: Descripción
          type: string
          description: Descripción breve del servicio
          default: Create a new Spring Boot microservice with Hexagonal Architecture
          ui:widget: textarea
          ui:options:
            rows: 3
        owner:
          title: Propietario
          type: string
          description: Nombre del propietario del componente
          default: platform-team
        email:
          title: Email del Propietario
          type: string
          description: Email de contacto del propietario
          format: email
          default: platform@addon-ai.com
    
    - title: Configuración Java
      properties:
        artifactId:
          title: Artifact ID
          type: string
          description: Artifact ID de Maven
          default: user-service
        javaVersion:
          title: Versión de Java
          type: string
          description: Versión de Java a utilizar
          default: "21"
          enum:
            - "17"
            - "21"
        springBootVersion:
          title: Versión de Spring Boot
          type: string
          description: Versión de Spring Boot
          default: "3.2.5"
          enum:
            - "3.2.5"
            - "3.3.0"
    
    
    - title: Repositorio
      required:
        - repoUrl
      properties:
        repoUrl:
          title: URL del Repositorio
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - addon-ai

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          email: ${{ parameters.email }}
          repoUrl: ${{ parameters.repoUrl }}
          version: "1.0.0"
          groupId: "com.example"
          artifactId: ${{ parameters.artifactId }}
          javaVersion: ${{ parameters.javaVersion }}
          springBootVersion: ${{ parameters.springBootVersion }}
          java_package_path: "com/example/userservice"
          database: "PostgreSQL"
          application_name: ${{ parameters.component_id | replace("-", "_") }}
          database_name: ${{ (parameters.component_id | replace("-", "_")) + "_db" }}
          port: 8080
          system: "user-system"
          lifecycle: "experimental"
          mapstructVersion: "1.5.5.Final"
          lombokVersion: "1.18.30"
          springdocVersion: "2.1.0"
          jacocoVersion: "0.8.11"
          lombokMapstructBindingVersion: "0.2.0"

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: private
        defaultBranch: main
    - id: create-develop
      name: Create develop Branch
      action: github:repo:create-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: develop
        sourceBranchName: main
    - id: create-test
      name: Create test Branch
      action: github:repo:create-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: test
        sourceBranchName: main
    - id: create-staging
      name: Create staging Branch
      action: github:repo:create-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: staging
        sourceBranchName: main
    - id: create-master
      name: Create master Branch
      action: github:repo:create-branch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: master
        sourceBranchName: main
    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
    
    - id: create-pr-develop
      name: Create Pull Request to Develop
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: feature/initial-setup
        targetBranchName: develop
        title: 'feat: Initial project setup from Backstage'
        description: |
          ## 🎉 Initial Project Setup
          
          This PR contains the initial project structure generated by Backstage.
          
          ### 🏛️ Architecture
          - **Pattern:** Hexagonal Architecture (Ports and Adapters)
          - **Framework:** Spring Boot ${{ parameters.springBootVersion }} with springBoot
          - **Java Version:** ${{ parameters.javaVersion }}
          
          ### 📦 Components
          - **Domain Layer:** Business logic and entities
          - **Application Layer:** Use cases and ports
          - **Infrastructure Layer:** Adapters and configurations
          
          ### 🚀 Next Steps
          1. Review the generated code structure
          2. Configure environment variables
          3. Run tests: `mvn test`
          4. Start application: `mvn spring-boot:run`

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Pull Request
        url: ${{ steps['create-pr-develop'].output.remoteUrl }}
