apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-templates-components
  description: All template components
spec:
  targets:
    - ./back-ms-users/catalog-info.yml
    - ./back-ms-movies/catalog-info.yml
    - ./back-ms-users-webflux/catalog-info.yml
    - ./back-ms-movies-webflux/catalog-info.yml