---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform engineering team responsible for developer tools and templates
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hexagonal-architecture-templates
  description: |
    Spring Boot service templates with Hexagonal Architecture (Ports and Adapters).
    Includes both traditional Spring Boot and reactive WebFlux implementations.
  tags:
    - backstage
    - templates
    - java
    - spring-boot
    - webflux
    - hexagonal-architecture
    - microservices
  links:
    - title: Documentation
      url: https://github.com/addon-ai/backstage-templates/blob/main/README.md
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
    backstage.io/techdocs-ref: url:https://github.com/addon-ai/backstage-templates/tree/main
spec:
  type: template-collection
  owner: group:default/platform-team
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-service-template
  description: Java Spring Boot microservice template with hexagonal architecture
  tags:
    - java
    - spring-boot
    - hexagonal-architecture
    - template
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: template
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/hexagonal-architecture-templates
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-domain-layer
  description: Domain layer - Business logic and entities for Spring Boot template
  tags:
    - domain
    - business-logic
    - entities
    - hexagonal-architecture
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/springboot-service-template
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-application-layer
  description: Application layer - Use cases, DTOs, mappers and services for Spring Boot template
  tags:
    - application
    - use-cases
    - services
    - dto
    - mappers
    - hexagonal-architecture
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/springboot-service-template
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-infrastructure-layer
  description: Infrastructure layer - Adapters, persistence, REST controllers and configuration for Spring Boot template
  tags:
    - infrastructure
    - adapters
    - persistence
    - rest-controllers
    - configuration
    - hexagonal-architecture
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/springboot-service-template
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-service-template
  description: Reactive Spring WebFlux microservice template with hexagonal architecture
  tags:
    - java
    - spring-boot
    - webflux
    - hexagonal-architecture
    - reactive
    - template
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: template
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/hexagonal-architecture-templates
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-domain-layer
  description: Domain layer - Business logic and entities for WebFlux reactive template
  tags:
    - domain
    - business-logic
    - entities
    - hexagonal-architecture
    - reactive
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/webflux-service-template
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-application-layer
  description: Application layer - Reactive use cases, DTOs, mappers and services for WebFlux template
  tags:
    - application
    - use-cases
    - services
    - dto
    - mappers
    - hexagonal-architecture
    - reactive
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/webflux-service-template
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-infrastructure-layer
  description: Infrastructure layer - Reactive adapters, R2DBC persistence, WebFlux handlers and configuration
  tags:
    - infrastructure
    - adapters
    - r2dbc
    - persistence
    - webflux-handlers
    - configuration
    - hexagonal-architecture
    - reactive
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: library
  owner: group:default/platform-team
  lifecycle: production
  subcomponentOf: component:default/webflux-service-template