apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: movies-system
  description: Movies management system
spec:
  owner: platform-team\n---\napiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: users-system
  description: Users management system
spec:
  owner: platform-team\n