apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: A service for managing user accounts with full CRUD operations and search capabilities. This service provides comprehensive user management functionality including user registration and authentication, profile management and updates, user search and listing with pagination, and account status management (active, inactive, suspended).
spec:
  type: openapi
  lifecycle: experimental
  owner: platform-team
  system: examples
  definition:
    $text: ../openapi/UserService.openapi.json
