apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 
  description: 
  tags:
    - java
    - springBoot
    - hexagonal-architecture
    - template
  annotations:
    github.com/project-slug: addon-ai/backstage-templates
spec:
  type: template
  owner: 
  lifecycle: production
  subcomponentOf: hexagonal-architecture-templates
