apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hex-arch-infrastructure-layer
  description: Capa de infraestructura (adaptadores, repositorios, configuración).
  tags:
    - hexagonal-architecture
    - infrastructure-layer
spec:
  type: service-part 
  owner: platform-team
  lifecycle: production
  
  partOf:
    - hexagonal-architecture-templates