apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: back-ms-movies-webflux
  title: Reactive microservice for movie rental management with Spring WebFlux
  description: Reactive microservice for movie rental management with Spring WebFlux
  tags:
    - java
    - springWebflux
    - hexagonal-architecture
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Información del Componente
      required:
        - component_id
        - owner
        - system
      properties:
        component_id:
          title: Nombre del Componente
          type: string
          description: Identificador único del componente (ej. user-service)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Usar kebab-case: minúsculas y guiones'
        description:
          title: Descripción
          type: string
          description: Descripción breve del servicio
          ui:widget: textarea
          ui:options:
            rows: 3
        owner:
          title: Propietario
          type: string
          description: Equipo propietario del componente
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        system:
          title: Sistema
          type: string
          description: Sistema al que pertenece el componente
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System
        lifecycle:
          title: Ciclo de Vida
          type: string
          description: Estado del ciclo de vida del componente
          default: experimental
          enum:
            - experimental
            - production
            - deprecated
          enumNames:
            - 'Experimental - En desarrollo'
            - 'Production - En producción'
            - 'Deprecated - Obsoleto'
        tags:
          title: Etiquetas
          type: array
          description: Etiquetas para clasificar el componente
          items:
            type: string
          default:
            - java
            - spring-boot
            - springWebflux
            - hexagonal-architecture
          ui:options:
            orderable: false
    
    - title: Configuración Java
      required:
        - groupId
        - artifactId
      properties:
        groupId:
          title: Group ID
          type: string
          description: Group ID de Maven (ej. com.example)
          default: com.example
        artifactId:
          title: Artifact ID
          type: string
          description: Artifact ID de Maven
          default: back-ms-movies-webflux
        javaVersion:
          title: Versión de Java
          type: string
          description: Versión de Java a utilizar
          default: "21"
          enum:
            - "17"
            - "21"
        springBootVersion:
          title: Versión de Spring Boot
          type: string
          description: Versión de Spring Boot
          default: "3.2.5"
          enum:
            - "3.2.5"
            - "3.3.0"
    
    - title: Configuración de Base de Datos
      required:
        - database
      properties:
        database:
          title: Base de Datos
          type: string
          description: Motor de base de datos
          default: PostgreSQL
          enum:
            - PostgreSQL
            - MySQL
            - H2
        enableLiquibase:
          title: Habilitar Liquibase
          type: boolean
          description: Usar Liquibase para migraciones
          default: true
    
    - title: Características Adicionales
      properties:
        enableSwagger:
          title: Habilitar Swagger/OpenAPI
          type: boolean
          description: Documentación API con SpringDoc
          default: true
        enableActuator:
          title: Habilitar Spring Actuator
          type: boolean
          description: Endpoints de monitoreo y salud
          default: true
        enableSecurity:
          title: Habilitar Spring Security
          type: boolean
          description: Seguridad y autenticación
          default: false
        coverageThreshold:
          title: Umbral de Cobertura
          type: number
          description: Porcentaje mínimo de cobertura de código
          default: 85
          minimum: 0
          maximum: 100
    
    - title: CI/CD y DevOps
      properties:
        enableGithubActions:
          title: Habilitar GitHub Actions
          type: boolean
          description: Pipeline CI/CD con GitHub Actions
          default: true
        enableDocker:
          title: Habilitar Docker
          type: boolean
          description: Dockerfile y docker-compose
          default: true
        environments:
          title: Ambientes
          type: array
          description: Ambientes de despliegue
          default:
            - local
            - develop
            - test
            - staging
            - prod
          items:
            type: string
    
    - title: Repositorio
      required:
        - repoUrl
      properties:
        repoUrl:
          title: URL del Repositorio
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - addon-ai

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          javaVersion: ${{ parameters.javaVersion }}
          springBootVersion: ${{ parameters.springBootVersion }}
          java_package_path: ${{ (parameters.groupId | replace(".", "/")) + "/" + (parameters.component_id | replace("-", "")) }}
          java_package_name: ${{ parameters.groupId + "." + (parameters.component_id | replace("-", "")) }}
          database: ${{ parameters.database }}
          enableLiquibase: ${{ parameters.enableLiquibase }}
          enableSwagger: ${{ parameters.enableSwagger }}
          enableActuator: ${{ parameters.enableActuator }}
          enableSecurity: ${{ parameters.enableSecurity }}
          coverageThreshold: ${{ parameters.coverageThreshold }}
          enableGithubActions: ${{ parameters.enableGithubActions }}
          enableDocker: ${{ parameters.enableDocker }}
          environments: ${{ parameters.environments }}
          application_name: ${{ parameters.component_id | replace("-", "_") }}
          database_name: ${{ (parameters.component_id | replace("-", "_")) + "_db" }}
          port: 8080

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: private
        defaultBranch: main
        gitAuthorName: Backstage Scaffolder
        gitAuthorEmail: scaffolder@backstage.io

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
    
    - id: create-pr-develop
      name: Create Pull Request to Develop
      action: publish:github:pull-request
      if: ${{ parameters.enableGithubActions }}
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: feature/initial-setup
        targetBranchName: develop
        title: 'feat: Initial project setup from Backstage'
        description: |
          ## 🎉 Initial Project Setup
          
          This PR contains the initial project structure generated by Backstage.
          
          ### 🏛️ Architecture
          - **Pattern:** Hexagonal Architecture (Ports and Adapters)
          - **Framework:** Spring Boot ${{ parameters.springBootVersion }} with springWebflux
          - **Java Version:** ${{ parameters.javaVersion }}
          
          ### 📦 Components
          - **Domain Layer:** Business logic and entities
          - **Application Layer:** Use cases and ports
          - **Infrastructure Layer:** Adapters and configurations
          
          ### 🛠️ Features
          - Database migrations with Liquibase: ${{ parameters.enableLiquibase }}
          - API documentation with Swagger: ${{ parameters.enableSwagger }}
          - Monitoring with Actuator: ${{ parameters.enableActuator }}
          - Code coverage threshold: ${{ parameters.coverageThreshold }}%
          
          ### 🚀 Next Steps
          1. Review the generated code structure
          2. Configure environment variables
          3. Run tests: `mvn test`
          4. Start application: `mvn spring-boot:run`

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Pull Request
        url: ${{ steps['create-pr-develop'].output.remoteUrl }}
        if: ${{ parameters.enableGithubActions }}
