apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: back-ms-movies-webflux
  title: WebFlux Reactive Microservice Template
  description: Template for generating WebFlux reactive microservices with Hexagonal Architecture
  tags:
    - java
    - webflux
    - hexagonal-architecture
spec:
  owner: user:guest
  type: service
  
  parameters:
    - title: Información del Componente
      required:
        - component_id
        - owner
        - system
      properties:
        component_id:
          title: Nombre del Componente
          type: string
          description: Identificador único del componente (ej. user-service)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Usar kebab-case: minúsculas y guiones'
        description:
          title: Descripción
          type: string
          description: Descripción breve del servicio
          ui:widget: textarea
          ui:options:
            rows: 3
        owner:
          title: Propietario
          type: string
          description: Equipo propietario del componente
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        system:
          title: Sistema
          type: string
          description: Sistema al que pertenece el componente
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: private
        defaultBranch: main

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}